##SPARQL
#http://sparql.wikipathways.org
##DESCRIPTION
# This query extracts from Wikipathways all simple interactions. These are relationships between one input and one output pathway element
##DATATYPES
#Geneproducts, Metabolites, Complex

