##SPARQL
#http://sparql.wikipathways.org
##DESCRIPTION
# This query extracts from Wikipathways element that are inhibited by a given source. These are relationships between one input and one output pathway element
##DATATYPES
#Geneproducts, Proteins
##MENU_LABEL
# inhibits

SELECT * WHERE
{
    ?interaction a wp:Inhibition ;
               wp:source ?source ;
               wp:target ?target .
    ?source dcterms:identifier ?sourceID .
    ?target dcterms:identifier +inputID+ .
}