##SPARQL
#http://sparql.uniprot.org/sparql/
##DESCRIPTION
# This query extracts from Wikipathways all simple interactions. These are relationships between one input and one output pathway element
##DATATYPES
#Proteins
##MENU_LABEL
# Get Protein-Enzyme Interactions

PREFIX taxon:<http://purl.uniprot.org/taxonomy/>  
PREFIX uniprotkb:<http://purl.uniprot.org/uniprot/> 
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#> 
PREFIX up:<http://purl.uniprot.org/core/> 
SELECT DISTINCT ?enzyme ?label WHERE {
	VALUES ?protein {uniprotkb:+inputID+}
	?protein up:enzyme ?enzyme .
	?protein rdfs:label ?label .
	?protein up:organism taxon:+taxon+ .
}

